Cv balldetection
Tino-FRC-2473/FRC2022-Vision pull request #3
Opened 2022-01-30 01:54 UTC by Shrinandan-N

This includes implementation of ball localization and angle calculations

2022-01-31 01:44 UTC, AG6GR requested changes
Please put images in Drive, not in Github. As noted before, git is not well suited for handling large binary files such as images.

2022-01-31 01:44 UTC, AG6GR commented on .idea/.gitignore
> +# Default ignored files
Can you add `.idea` to the top level `.gitignore` file? That should remove these temporary files.

2022-01-31 01:44 UTC, AG6GR commented on ball_detection.py
> +    def find_angle(self, x, y):
This is finding the angle with respect to the image right? But in reality we want the angle with respect to the robot. Might be helpful to draw a diagram from the side of the robot to visualize what these look like.

2022-01-31 01:44 UTC, AG6GR commented on ball_detection.py
> +    def find_angle(self, x, y):
We can talk more about this over the next week, doesn't have to be fixed in this PR.

2022-02-03 05:34 UTC, tsoim commented on ball_detection.py
> +                    if len(borders) > 6:
magic num :(

2022-02-03 05:34 UTC, tsoim commented on run.py
> +img = cv2.imread("test_images/dis48_angle10.png")
you could try and make this script take in an argument so you can pass in the filename. I like this package a lot: https://click.palletsprojects.com/en/8.0.x/ or there's also https://docs.python.org/3/library/argparse.html

2022-02-16 05:19 UTC, AG6GR approved these changes

2022-02-16 05:47 UTC, merged